[ feat ] Reservation Page Top
SOPT-all/35-COLLABORATION-WEB-SKYSCANNER pull request #27
Opened 2024-11-21 18:01 UTC by heesunee

## 🔥 Related Issues

- close #16 

## ✅ 작업 리스트

- [x] 지역, 필터 선택 컴포넌트
- [x] 광고 컴포넌트
- [x] 추천순, 최단시간순 탭 컴포넌트

## 🔧 작업 내용
- 네이밍은 피그마를 기준으로 지었습니다!
- 이정도로 top을 묶으면 적당한 이슈 단위라 생각했는데..... 안에서 처리할 값이 많아서 작성 내용이 많습니다. 읽어보시고 피드백 많이 많이 남겨주세요!

1. TopBar 부분
![image](https://github.com/user-attachments/assets/5da95f66-f3fc-4076-ac90-d04485af8893)

- 원래는 지역을 선택할 수 있게 처리를 해야하지만, 현재 기능에는 서울 - 오키나와 지역을 고정하기로 했으므로 그냥 `div`와 `span` 태그로 처리했습니다.
- 밑의 필터링 부분에서 날짜를 제외한 사람과 좌석은 선택 기능이 없기 때문에 또 div와 span으로 처리했습니다.
- 날짜 선택 버튼은 우선 날짜를 보여주는 기능만 작업했습니다. 선택 시 나타나는 화면은 추후 구현예정입니다.
- Home에서 선택한 날짜가 '2024-11-3'과같은 string으로 값이 전달될 것이라 생각했기 때문에 이를   nn월 nn일 (n)을 출력하기 위해 변환하는 함수 formatDate를 utils 폴더에 추가했습니다.

```ts
/**
 * 날짜를 nn월 nn일 (n)을 출력하기 위해 변환하는 함수
 * @param date - 변환할 날짜의 문자열을 받음 (ex: 2024-11-03)
 * @returns { month: number, day: number, weekday: string}
 */

export const formatDate = (date: string) => {
	const dateObj = new Date(date);
	const weekdays = ['일', '월', '화', '수', '목', '금', '토'];

	const month = dateObj.getMonth() + 1;
	const day = dateObj.getDate();
	const weekday = weekdays[dateObj.getDay()];

	return { month, day, weekday };
};

```
- DateFilter 컴포넌트에서는 전달받은 값을 해당 함수를 이용해 값을 월, 일, 요일로 변환하여 두 DateButton 각각에 시작 날짜와 종료 날짜를 렌더링 합니다.

2.  TabFlight 부분
![image](https://github.com/user-attachments/assets/7bc8bf68-e007-4e37-ac37-66db69ce66f1)

- 정렬은 구현하지 않기로 했기 때문에, 단순 텍스트로 처리했습니다.
- mock 폴더에 항공권 조회에 대한 목업 데이터와 그에 대한 type을 type 폴더에 추가했습니다. 아직 노션에 정리된 사항이 없기 때문에 임의로 작성했습니다. 

```ts
// mockFlightData.ts
export const flightData = [
	{
		id: 1,
		from: 'ICN',
		to: 'OKA',
		dep_time1: '2024-11-06 13:20',
		arr_time1: '2024-11-06 15:45',
		dep_time2: '2024-11-13 16:50',
		arr_time2: '2024-11-13 19:15',
		average_time: '2시간 30분',
		dep_price: 165000,
		arr_price: 107400,
		airline: '이스타 항공',
		is_like: false,
		count: 1,
	},

// FlightTypes.ts
export interface Flight {
	id: number;
	from: string;
	to: string;
	dep_time1: string;
	arr_time1: string;
	dep_time2: string;
	arr_time2: string;
	average_time: string;
	dep_price: number;
	arr_price: number;
	airline: string;
	is_like: boolean;
	count: number;
}

```

- 밑의 추천순 - 최단시간을 Tab 하는 부분은 항공권 정보를 받아 가격과 시간에 대한 처리가 필요합니다. 따라서 utils  폴더에 filghtUtils.ts를 추가했습니다.
- `findCheapestFlgiht` 함수는 출발 가격+도착 가격을 더한 배열을 만들어 `Math.min`으로 최솟값을 찾습니다. 후의 작업을 통해 최소 가격에 해당하는 항공권의 `평균시간`과 `totalPrice`를 반환합니다.
- `findshortestFlight` 함수는 유사하게 항공권의 정보를 받습니다. 우선` average_time`이 '2시간 30분'과 같은 `string`으로 온다고 가정했기 때문에 이를 150분으로 변환하는 과정을 거치고, 변환된 배열중에 `Math.min`을 사용해 최단 시간을 찾습니다. 
- 함수 설명 부분은 파일에 주석으로 상세하게 달아놓았으니 그 부분을 참고하시면 될 것 같습니다.

## 🧐 새로 알게된 점
- variant props를 정의해 그 값에 따른 다른 스타일링을 보여주는 방법
- React.FC를 사용한 부분이 많았는데요, 사용을 지양하는 것이 좋다는 의견과 아티클을 보고 후다닥 바꿨습니다 !

## 🤔 궁금한 점
![image](https://github.com/user-attachments/assets/554081dc-5e28-43fe-960b-4d1c08ceecff)
- 위 컴포넌트는 스타일이 거의 비슷하지만 양 옆의 border-radius,  폰트 색상, 배경색상만 다른데요, 두개를 만들기보다 이를 한 컴포넌트 내에서 처리하고 싶어서 고민을 많이했습니다.
- 민정님 코드리뷰를 진행하면서 같은 버튼에 대한 미세하게 다른 스타일을 적용하는 방법을 보고, 추천순/최단시간 탭 컴포넌트에도 적용해보려고 했는데 이런 방법으로는 처음 작성해봐서... 한번 봐주시면 감사하겠습니다!!

// TabFlight.tsx
![image](https://github.com/user-attachments/assets/4b0516e1-6ae4-49a6-9ad8-6032026f55fa)

TabCard에는 총 4개의 값이 전달됩니다. 제목, 가격합계, 평균시간, 그리고 추천순/최단시간에 따라 스타일이 다르게 적용될 것이기 때문에 variant를 만들어 주었습니다.

```ts
interface TabCardProps {
	title: string;
	totalPrice: string;
	averageTime: string;
	variant: 'cheapest' | 'shortest';
}
```
- TabFlight에서 전달한 variant의 값을 TabCardContainer에서 사용합니다.
```ts
const TabCardContainer = styled.div<{ variant: 'cheapest' | 'shortest' }>`
	display: flex;
	align-items: center;
	justify-content: center;
	width: 18rem;
	height: 8.4rem;
	padding: 1.1rem 5rem;
	flex-direction: column;

	// 추천순일 때 적용될 css
	${({ variant }) =>
		variant === 'cheapest' &&
		css`
			background-color: ${({ theme }) => theme.colors.darksky};
			border-radius: 1rem 0rem 0rem 1rem;
			${Title}, ${Price}, ${Time} {
				color: ${({ theme }) => theme.colors.white}; /* cheapest일 때 텍스트 색상 */
			}
		`}

	// 최단시간일 때 적용될 css
	${({ variant }) =>
		variant === 'shortest' &&
		css`
			background-color: ${({ theme }) => theme.colors.white};
			border-radius: 0rem 1rem 1rem 0rem;
		`}
`;
```

- Title, Price, Time에 대한 컬러는 기본으로 최단시간일 때를 설정해 두었고, 추천순은 모든 색상이 흰색으로 통일되기 때문에 TabCardContainer 스타일 내에서 variant가 cheapest 이면 Title, price, time의 폰트 색상을 모두 흰색으로 사용하도록 설정했습니다.

## 📸 스크린샷 / GIF / Link
![image](https://github.com/user-attachments/assets/59ec70fc-ea38-4537-ac02-677fb6404e70)

2024-11-22 19:39 UTC, KIMGEONHWI requested changes
아직 항공권 조회 api 명세서가 나오지 않은 상태라 mock데이터 구현도 그렇고 쉽지 않은 부분이 많았을텐데 고생 많았어요. 코드리뷰 남긴 부분만 한번 확인해주세요!!

2024-11-22 19:39 UTC, KIMGEONHWI commented on src/components/reservation/DateFilter.tsx
> +				</>
p5: 혹시 이와 같은 빈태그는 영역을 구변하기 위함인가요?

2024-11-22 19:39 UTC, KIMGEONHWI commented on src/pages/reservation/index.tsx
해당 파일명 `reservation.tsx`로 수정 부탁드려요!

2024-11-22 19:39 UTC, KIMGEONHWI commented on src/types/FlightTypes.ts
p5: 타입 분리 굿굿

2024-11-22 19:39 UTC, KIMGEONHWI commented on src/components/reservation/TabCard.tsx
> +`;
p1: `Title`, `Price`, `Time` 부분의 폰트 피그마 참고하여 수정해주세요!!

2024-11-22 19:39 UTC, KIMGEONHWI commented on src/components/reservation/TabCard.tsx
> +`;
```suggestion
const TabCardContainer = styled.div<{ variant: 'cheapest' | 'shortest' }>`
   display: flex;
   align-items: center;
   justify-content: center;
   width: 18rem;
   height: 8.4rem;
   padding: 1.1rem 5rem;
   flex-direction: column;
   border-radius: ${({ variant }) =>
      variant === 'cheapest' ? '1rem 0rem 0rem 1rem' : '0rem 1rem 1rem 0rem'};
   background-color: ${({ theme, variant }) =>
      variant === 'cheapest' ? theme.colors.darksky : theme.colors.white};

   ${Title}, ${Price}, ${Time} {
      color: ${({ theme, variant }) =>
         variant === 'cheapest' ? theme.colors.white : theme.colors.black};
   }
`;
```
`variant`에 따른 스타일링이 중복되어 가독성이 많이 떨어지는 느낌이네요. 다음과 같이 기본 스타일을 추출하여 사용하면 가독성도 좋아지고 관리하기 편할 것 같아요.

2024-11-22 19:39 UTC, KIMGEONHWI commented on src/components/reservation/TabCard.tsx
> +`;
```suggestion
const Title = styled.h2<{ variant: 'cheapest' | 'shortest' }>`
   font-size: 1.2rem;
   font-weight: bold;
   margin-bottom: 0.7rem;
   color: ${({ theme, variant }) =>
      variant === 'cheapest' ? theme.colors.white : theme.colors.black};
`;
```
해당 부분도 `variant`에 따라 개별 스타일 적용 시키도록 하는게 좋아보여요!

2024-11-22 19:39 UTC, KIMGEONHWI commented on src/components/reservation/TabCard.tsx
> +`;
```suggestion
const Price = styled.p<{ variant: 'cheapest' | 'shortest' }>`
	font-size: 1.4rem;
	font-weight: bold;
	color: ${({ theme, variant }) =>
              variant === 'cheapest' ? theme.colors.white : theme.colors.skyblue}; /* 가격 색상 */
`;
```
해당 부분도 variant에 따라 개별 스타일 적용 시키도록 하는게 가독성 측면에서 더 좋을 것 같아요!

2024-11-22 19:39 UTC, KIMGEONHWI commented on src/components/reservation/TabCard.tsx
> +`;
```suggestion
const Time = styled.p<{ variant: 'cheapest' | 'shortest' }>`
	font-size: 1rem;
	color: ${({ theme, variant }) =>
              variant === 'cheapest' ? theme.colors.white : theme.colors.grey40};
	margin-top: 0.5rem;
`;
```
위 코드 부분도 다음과 같이 수정하면 좋을 것 같아요!

2024-11-23 06:31 UTC, KIMGEONHWI approved these changes
LGTM~

2024-11-25 06:21 UTC, ayla-12 commented on src/utils/dateUtils.ts
> + * @returns { month: number, day: number, weekday: string}
p5: 제가 이런 형태는 처음봐서 그런데 어떤 상황일 때 사용하는 코드인걸까요? 아래는 함수인 걸 알겠는데 해당 코드가 뭘 어떻게 다루는 건지 궁금해서요!

여담으로 Utils 따로 분리해놓아서 함수만 볼 수 있어서 좋은 것 같습니다 👍👍

2024-11-25 06:23 UTC, ayla-12 commented on src/router/Router.tsx
> +import Wish from '@/pages/wish/Wish';
p5: 꼼꼼한 정정... 근데 reservation은 앞글자가 소문자고 Wish는 앞글자가 대문자라서 이거 사소하지만 맞추면 좋을 것 같아요.. ㅋㅋㅋㅋ

2024-11-25 06:25 UTC, ayla-12 commented on src/pages/reservation/Reservation.tsx
> +		<ReservationContainer>
p5: 오호 Reservation 화면 코드에 바로 구현을 하셨군요!! 물론 잘 모르는 입장에서 하는 말이지만, 저는 page 코드에는 컴포넌트 명만 있는게 좀 더 가독성이 좋다고 생각하거든요. 혹시 이걸 분리하는 희선님만의 기준이 있으실까요?!?

2024-11-25 06:28 UTC, ayla-12 commented on src/components/reservation/DateFilter.tsx
> +				</>
p5: 영역을 구분하기 위함이라면 저는 이름 달아주면 더 좋을 것 같아요!!! 더 명시적이어서 읽기 쉬워질 것 같습니다.

2024-11-25 06:28 UTC, ayla-12 approved these changes
안녕하세요 희선님!!! 코리가 많이 늦었지요...ㅠㅠ 희선님 코드보면서 또 새로운 것들을 많이 배워갑니다!!!

2024-11-25 10:25 UTC, minjeoong reviewed
확인했습니다! 
수정할 건 거의 없어서 콘솔만 확인해주시면 좋을 것 같아요 !!

2024-11-25 10:25 UTC, minjeoong commented on src/components/reservation/DateFilter.tsx
> +				</>
p5: flex 때문에 그랬지 않을까 싶은데, 저도 이름 달아주면 좋을 것 같습니다 !!!!

2024-11-25 10:25 UTC, minjeoong commented on src/components/reservation/TabFlight.tsx
> +	console.log(shortestFlight);
p5: 콘솔도 지워주세요 !!

2024-11-25 10:25 UTC, minjeoong commented on src/utils/dateUtils.ts
> + * @returns { month: number, day: number, weekday: string}
이 코드는 쓰인다기 보단 다른 개발자분들이 해당 함수를 사용하게 될 수 있기 때문에 남겨두는 정보 에요!!

2024-11-25 10:25 UTC, minjeoong commented on src/utils/dateUtils.ts
> +};
p4: 오옷 저도 포맷하는 함수가 있어서 제 코드랑 중복 될 수 있을 것 같은데
나중에 머지하면서 제가 수정해서 올리겠습니다

2024-11-26 08:51 UTC, merged