[ Feat ] Wish 페이지 아티클 컴포넌트 구현
SOPT-all/35-COLLABORATION-WEB-SKYSCANNER pull request #29
Opened 2024-11-21 18:55 UTC by KIMGEONHWI

## 🔥 Related Issues

- close #24 

## ✅ 작업 리스트

- [ ] Wish 페이지 아티클 컴포넌트 구현

## 🔧 작업 내용
### mockWishList.ts
```typescript
export const mockWishList = [
	{
		id: 1,
		backgroundImageUrl: '',
		departure: '서울',
		arrival: '오키나와',
		airline: '제주항공',
		depFlightTimeline: 'PM1:20 - PM3:45',
		depFlightTime: '2시간 25분',
		depAirport: 'ICN-OKA',
		arrFlightTimeline: 'PM4:50 - PM7:15',
		arrFlightTime: '2시간 25분',
		arrAirport: 'OKA-ICN',
		travelDays: '10일 - 2025.2.13',
		person: 1,
		price: '₩277,700',
	},
	{
		id: 2,
		backgroundImageUrl: '',
		departure: '서울',
		arrival: '오키나와',
		airline: '진에어',
		depFlightTimeline: 'PM10:10 - PM12:30',
		depFlightTime: '2시간 20분',
		depAirport: 'ICN-OKA',
		arrFlightTimeline: 'PM1:30 - PM3:50',
		arrFlightTime: '2시간 20분',
		arrAirport: 'OKA-ICN',
		travelDays: '10일 - 2025.2.13',
		person: 1,
		price: '₩177,700',
	},
	{
		id: 3,
		backgroundImageUrl: '',
		departure: '서울',
		arrival: '오키나와',
		airline: '이스타항공',
		depFlightTimeline: 'AM11:35 - PM2:00',
		depFlightTime: '2시간 25분',
		depAirport: 'ICN-OKA',
		arrFlightTimeline: 'PM3:00 - PM6:30',
		arrFlightTime: '2시간 25분',
		arrAirport: 'OKA-ICN',
		travelDays: '10일 - 2025.2.13',
		person: 1,
		price: '₩133,800',
	},
];
```
`api` 명세서 참고하여, `Mock` 데이터 생성해주었습니다. 추후 `api` 연동시 빠르게 작업할 수 도록 해당 데이터를 이용하여 `map` 함수로 리스트를 렌더링하도록 하였습니다.

### WishContents.tsx
```typescript
import WishContentCard from './WishContentCard';
import { mockWishList } from '@/mocks/mockWishList';
import styled from 'styled-components';

const WishContents = () => {
	return (
		<WishContentsWrapper>
			{mockWishList.map((item) => (
				<WishContentCard key={item.id} {...item} />
			))}
		</WishContentsWrapper>
	);
};

export default WishContents;

const WishContentsWrapper = styled.div`
	display: flex;
	flex-direction: column;
	gap: 0.9rem;
`;
```
`map` 함수로 리스트를 렌더링하는 루트 컴포넌트

### FlightInfo.tsx
```typescript
import JejuAirIcon from '@/assets/svg/ic_jejuair.svg?react';
import styled from 'styled-components';

interface FlightInfoProps {
	timeline: string;
	route: string;
	airline: string;
	option: string;
	duration: string;
}

const FlightInfo = ({ timeline, route, airline, option, duration }: FlightInfoProps) => {
	return (
		<FlightInfoSection>
			<JejuAirIcon />
			<FlightInfoSectionMid>
				<DepFlightTimeline>{timeline}</DepFlightTimeline>
				<RouteAirlineBox>
					<OriginDestination>{route}</OriginDestination>
					<Airline>, {airline}</Airline>
				</RouteAirlineBox>
			</FlightInfoSectionMid>
			<WishContentsTimeSectionRight>
				<FlightOption>{option}</FlightOption>
				<FlightTime>{duration}</FlightTime>
			</WishContentsTimeSectionRight>
		</FlightInfoSection>
	);
};

export default FlightInfo;

const FlightInfoSection = styled.div`
	display: flex;
	gap: 1.6rem;
`;

const FlightInfoSectionMid = styled.div`
	display: flex;
	flex-direction: column;
`;

const DepFlightTimeline = styled.p`
	width: 12.6rem;
	${({ theme }) => theme.fonts.e_body_b_16};
`;

const RouteAirlineBox = styled.div`
	display: flex;
	align-items: center;
	width: 10rem;
`;

const OriginDestination = styled.p`
	${({ theme }) => theme.fonts.e_body_m_12};
`;

const Airline = styled.p`
	${({ theme }) => theme.fonts.body6_r_12};
`;

const WishContentsTimeSectionRight = styled.div`
	display: flex;
	flex-direction: column;
	padding-left: 6.4rem;
`;

const FlightOption = styled.p`
	${({ theme }) => theme.fonts.body3_sb_12};
	text-align: right;
`;

const FlightTime = styled.p`
	${({ theme }) => theme.fonts.e_body_m_12};
	color: ${({ theme }) => theme.colors.grey40};
`;
```
<img width="466" alt="스크린샷 2024-11-22 오전 3 50 30" src="https://github.com/user-attachments/assets/63c0c456-d889-4322-83e6-683827c22453">
위의 사진이 `FlightInfo`컴포넌트의 `UI`인데, 2번 반복되어서 사용되므로 분리하여 재사용 할 수 있게 하였습니다.

## 🧐 새로 알게된 점
**HTML의 id 속성은 항상 문자열(string)만 허용한다**
해당 내용 트러블 슈팅에 작성하였습니다.(링크 참고)
https://www.notion.so/13b205f6a10581ea84e8cc1efa58d222?p=145205f6a105809b808dc7f9306c0967&pm=s

## 🤔 궁금한 점
제 나름대로의 기준으로 컴포넌트 분리를 진행하였는데, 피드백 해주실 사항있으면 해주세요!
## 📸 스크린샷 / GIF / Link
https://github.com/user-attachments/assets/dca3242a-7737-47f3-90a2-e501b5bb368b

현재 하트 아이콘 클릭시 빈하트가 되는 아이콘이 아직 준비가 안되어있어서, 디자이너분께 요청하여 빈하트 svg를 얻게되면 추후에 하트 토클 구현 예정입니다.

2024-11-22 10:35 UTC, heesunee requested changes
고생많으셨습니다! 사실 위시리스트카드를 map으로 계속 보여주는 것과, 항공권 조회 페이지 내에서 각 항공권 카드들을 map으로 보여주고 그 외의 디자인이나 값을 띄우는 부분도 유사한 점이 많아 많은 공부가 되었습니다.ㅎㅎ
 근데 지금 각기 다른 항공사 airline의 경우에도 같은 항공사 아이콘을 보여주고 있는 것 같아서 이 부분만 수정해주시면 될 것 같습니다!

2024-11-22 10:35 UTC, heesunee commented on src/components/wish/FlightDetails.tsx
> +			</PersonSeatWrapper>
p5: 질문입니다!!!
제가 작성한 항공권 컴포넌트와 유사한 디자인이라 여쭤봅니다
현재 personInfo에 값이 '성인 1명, 일반석' 형태로 한 문장으로 전달되고 있는데, 원래 디자인은 여기서 각각의 구성 요소가 다른 스타일을 사실 사용하고 있어요. 
- 숫자 (1)는 e_body_m_12 폰트를 사용해야 하고
- 텍스트 (성인, 일반석)은 body6_r_12 폰트를 사용해야 하는 상황입니다.  
제 담당 부분에서도 한 문장안에서 영어, 숫자, 한글이 서로 다른 폰트(한글자임에도 불구하고)를 사용하는 경우가 많아 매번 StyledSpan으로 감싸서 처리했는데요.. 이 부분을 크게 신경쓰지않고 전체로 하나의 스타일로 처리해도 괜찮을까요? ㅜㅜ

2024-11-22 10:35 UTC, heesunee commented on src/components/wish/FlightInfo.tsx
> +			</FlightInfoSectionMid>
p1: 각 다른 항공사의 경우에도 모두 제주항공의 아이콘을 띄우는 것으로 보입니다!

2024-11-22 10:35 UTC, heesunee commented on src/components/wish/ToggleSwitch.tsx
> +`;
p5: 토글 버튼 클릭시 전환이 어떻게 구현되나 궁금했는데, trainsition 등을 사용해서 자연스럽게 구현할 수 있군요!!

2024-11-22 10:35 UTC, heesunee commented on src/components/wish/WishContents.tsx
p5: 저는 항공권 조회의 index.tsx 내에서 map 함수를 돌렸는데, 이렇게 분리하셨네요!! 참고해가겠습니다 ~~ ㅎㅎ

2024-11-22 10:35 UTC, heesunee commented on src/mocks/mockWishList.ts
p5: 나도 조회 api 값 빨리 주면 좋겠다 .......... 아마 비슷할 것 같은데..... 흑흑

2024-11-22 19:40 UTC, KIMGEONHWI commented
> 고생많으셨습니다! 사실 위시리스트카드를 map으로 계속 보여주는 것과, 항공권 조회 페이지 내에서 각 항공권 카드들을 map으로 보여주고 그 외의 디자인이나 값을 띄우는 부분도 유사한 점이 많아 많은 공부가 되었습니다.ㅎㅎ 근데 지금 각기 다른 항공사 airline의 경우에도 같은 항공사 아이콘을 보여주고 있는 것 같아서 이 부분만 수정해주시면 될 것 같습니다!

해당 부분은 서버분들과 논의해야 되는 부분이 있어서 현재 제주항공만 넣어놓은 상태입니다! 꼼꼼하게 확인해주셔서 감사합니다.

2024-11-22 19:42 UTC, KIMGEONHWI commented on src/components/wish/FlightDetails.tsx
> +			</PersonSeatWrapper>
> p5: 질문입니다!!! 제가 작성한 항공권 컴포넌트와 유사한 디자인이라 여쭤봅니다 현재 personInfo에 값이 '성인 1명, 일반석' 형태로 한 문장으로 전달되고 있는데, 원래 디자인은 여기서 각각의 구성 요소가 다른 스타일을 사실 사용하고 있어요.
> 
> * 숫자 (1)는 e_body_m_12 폰트를 사용해야 하고
> * 텍스트 (성인, 일반석)은 body6_r_12 폰트를 사용해야 하는 상황입니다.
>   제 담당 부분에서도 한 문장안에서 영어, 숫자, 한글이 서로 다른 폰트(한글자임에도 불구하고)를 사용하는 경우가 많아 매번 StyledSpan으로 감싸서 처리했는데요.. 이 부분을 크게 신경쓰지않고 전체로 하나의 스타일로 처리해도 괜찮을까요? ㅜㅜ

사실 `StyledSpan`감싸서 처리하는 것이 맞는데요. 해당 부분에서 너무 많은 리소스를 투자할 것 같아 현재는 하나의 스타일로 처리해 놓은 상태입니다. 디자이너분들과 한번 이야기해볼게요!

2024-11-22 19:42 UTC, KIMGEONHWI commented on src/components/wish/FlightInfo.tsx
> +			</FlightInfoSectionMid>
> p1: 각 다른 항공사의 경우에도 모두 제주항공의 아이콘을 띄우는 것으로 보입니다!

해당 부분은 서버분들과 논의해야 되는 부분이 있어서 현재 제주항공만 넣어놓은 상태입니다! 꼼꼼하게 확인해주셔서 감사합니다.

2024-11-23 17:58 UTC, ayla-12 approved these changes
희선님이 꼼꼼하게 봐주신 것 같아서!!! LGTM 남깁니다~~

2024-11-23 18:53 UTC, merged