[ Feat ] 항공권 컴포넌트 퍼블리싱
SOPT-all/35-COLLABORATION-WEB-SKYSCANNER pull request #31
Opened 2024-11-22 12:54 UTC by heesunee

## 🔥 Related Issues

- close #28 
- 
## ✅ 작업 리스트

- [x] 항공권 컴포넌트 퍼블리싱

## 🔧 작업 내용
- FlightCard.tsx -> 항공권 카드
- FlightList.tsx -> flightData를 map으로 돌면서 카드 리스트를 반환
- Icons.tsx -> ! 아이콘과 하트 아이콘에 대한 각각의 함수
- Info -> 출발 시간, 도착시간을 나타내는 정보가 같은 디자인으로 두번 사용되어 컴포넌트로 분리했습니다.
- -PriceSelect -> 합계 가격과 선택하기 버튼이 분리되어있습니다.

항공권 조회시 나오는 항공권 컴포넌트를 퍼블리싱 했습니다. 자잘한 스타일 때문에 개개개 노가다한 부분이 많아서....... 많이 지저분합니다 ㅜㅜ

- ! 느낌표 아이콘 클릭시 ToolTip바가 보입니다. 다시 클릭하면 없어집니다.
- 하트 아이콘을 클릭하면 채워진 아이콘으로 바뀝니다. handleHeartClick 함수로 구현되어있으며  후에 이곳에서 위시리스트와 동기화하는 API 작업을 추가하면 될 것 같습니다.

## 🧐 새로 알게된 점

### Record
Record는 TypeScript에서 특정 타입의 키에 대해 특정 타입의 값을 갖는 객체를 생성할 수 있는 유틸리티 타입입니다. `Record<K, T>` 과 같은 형식을 따릅니다. JSX.Element와 결합하여 사용할 수 있다는 것을 처음 알게 되었습니다.
항공사 아이콘이 svg파일로 이미 만들어져있기 때문에, 파일 내에서 import할때는 <EastarIcon />과 같이 JSX.Element로 사용하게 됩니다. '이스타 항공' 일때 항공사의 이름 옆에 <EasterIcon />이 들어갈 수 있는 방법이 없을까 찾아보다가 알게되었습니다.

```ts
// 항공사 이름을 키로, JSX.Element를 값으로 하는 객체
const airlineIcons: Record<string, JSX.Element | undefined> = {
  '이스타 항공': <EastarIcon />,
  '대한항공 (KAL)': <KalIcon />,
  진에어: <JinAirIcon />,
  제주항공: <JejuAirIcon />,
};
```

임의로 네 항공사를 추가해두었습니다. 해당 항공사의 아이콘이 없다면 undefined를 반환합니다.

`{airlineIcons[airline] || null}`
airlineIcons 객체에서 항공사이름에 해당하는 아이콘(키)를 찾고, 그에 해당하는 JSX.Element를 반환합니다.

## 🤔 궁금한 점
- 이 ToolTip이 참 까다로웠는데요... 우선 useState를 사용해 visible의 값을 바꾸며 보이게 설정했습니다. 피그마에서 직사각형과 세모 폴리곤이 결합된 도형이라... relative - position을 이용해 개 노가다로 위치를 지정했습니다... 하하

```ts
/// ....
	const handleHeartClick = () => {
		setIsLike((prev) => !prev);
		// 위시리스트 API 연결작업
		// ...
	};
	const handleExclamationClick = () => {
		setIsTooltipVisible((prev) => !prev);
		console.log(isTooltipVisible);
	};
///
///......
	<IconContainer>
					{isTooltipVisible && (
						<ToolTipContainer onClick={handleExclamationClick} style={{ cursor: 'pointer' }}>
							<ToolTip>
								<FlightIcon />
								<StyledSpan>같은 노선의 항공편보다 이산화탄소 환산량이 </StyledSpan>
								<StyledSpan isNumber>36%</StyledSpan>
								<StyledSpan>더 적은 친환경 항공편이에요!</StyledSpan>
							</ToolTip>
							<PolyGonContainer>
								<PolygonIcon />
							</PolyGonContainer>
						</ToolTipContainer>
					)}

					<ExclamationIcon onClick={handleExclamationClick} style={{ cursor: 'pointer' }} />

					{isLike ? (
						<HeartBlackIcon onClick={handleHeartClick} style={{ cursor: 'pointer' }} />
					) : (
						<HeartIcon onClick={handleHeartClick} style={{ cursor: 'pointer' }} />
					)}
				</IconContainer>
```

코드에서 PolyGonConatiner와 ToolTipContainer를 보시면 top -7%, left:-1.3 이런식으로 맞춰져 있는데, 다른분들은 이 디자인을 어떤식으로 구현할 생각을 하시는 지 궁금합니다. 그리고 ToolTip 내 폰트를 피그마와 똑같이 설정해도 훨씬 커보여서 가로 폭이 늘어났습니다.

### `new Intl.NumberFormat(locales, options)`

(+추가 이 부분 코드를 작성하기 시작할 때, 아직 항공권 조회 시의 성공 값이 노션에 적혀있지 않았습니다. 출발 가격, 도착 가격이 따로따로 온다고 생각해서 mockdata도 그렇게 적어놓고 여기도 합계를 구한뒤 200,000의 형식으로 포맷해야한다고 생각했는데 wishlist api 반환 값을 보니 그냥 두개를 더한 값이 편하게 나오는 것 같네요 ... ㅜㅜ 그 외의 다른 값들도 편하게 오네요. ㅎㅎ 후에 수정하겠습니다 ...)

해당 객체는 숫자를 지역화된 형식으로 포맷할 수 있도록 합니다.
locales에는 언어와 지역, options에는 숫자를 어떻게 포맷할지에 대한 옵션입니다.
출발가격과 도착 가격을 더한 총 합을 구해야 하는데요, 160000+100000 => 260000원이면 여기서 쉼표 표시를 해줘야 했기 때문에 1000 단위로 나눠야 하나 고민하던 도중 알게 되었습니다.

`const formatPrice = (price: number) => new Intl.NumberFormat('ko-KR', { style: 'decimal' }).format(price);`
price를 한국어 형식(대한민국지역)으로 일반적인 숫자형식으로 포맷하는 함수입니다. 'decimal': 기본적인 숫자 포맷을 사용하겠다는 의미입니다. 예를 들어, 1000을 1,000으로 포맷합니다. 다른 스타일로는 'currency'(통화 형식), 'percent'(백분율 형식) 등이 있습니다

## 📸 스크린샷 / GIF / Link

- 배경색은 컴포넌트를 확실히 구분하기 위해 임의로 깔아둔 것입니다. 마지막 커밋때 지워진 상태입니다~~

https://github.com/user-attachments/assets/0125e6e0-72be-44dc-b7bf-9c50d44ea17f

2024-11-23 17:52 UTC, KIMGEONHWI requested changes
디테일한 부분이나, 특히 툴팁 같은 경우에 쉽지 않았을텐데 고생하셨어요.
코드리뷰 부분만 한번 확인해주세요!

2024-11-23 17:52 UTC, KIMGEONHWI commented on src/components/reservation/FlightCard.tsx
> +import Info from './Info';
p5: 절대경로로 수정해주세요

2024-11-23 17:52 UTC, KIMGEONHWI commented on src/components/reservation/FlightCard.tsx
> +};
p5: 저도 해당 부분에 대한 고민이 많았었는데, 희선님과 같이 `Record`를 사용하면 되겠군요.

2024-11-23 17:52 UTC, KIMGEONHWI commented on src/components/reservation/FlightCard.tsx
> +		console.log(isTooltipVisible);
p5: 필요 없는 부분이라면 콘솔은 지워주세요!

2024-11-23 17:52 UTC, KIMGEONHWI commented on src/components/reservation/Icons.tsx
p1: 해당 파일에서 인라인 스타일 적용되어 있는 부분은 `styled-components`로 분리하는 것이 좋을 것 같습니다.
```style={{ cursor: 'pointer' }}```

2024-11-23 17:52 UTC, KIMGEONHWI commented on src/components/reservation/Icons.tsx
> +			)}
p3: 취향 차이긴한데, 삼항 연산자를 사용하지 않고 다음과 같이 `isLike` 값을 활용해 코드를 간소화 하는 방법도 있습니다.
```suggestion
const HeartIconComponent = isLike ? HeartBlackIcon : HeartIcon;

<HeartIconComponent onClick={handleHeartClick} style={{ cursor: 'pointer' }} />
```

2024-11-23 17:52 UTC, KIMGEONHWI commented on src/components/reservation/FlightCard.tsx
> +			<Rectangle />
p2: `<Rectangle />`를 따로 만들어서 위치시키는 것 보다는, `PriceSelect` 컴포넌트에 `border-top` 속성을 주어서 스타일링 하는 것이 좋아보여요!

2024-11-25 10:42 UTC, heesunee commented on src/components/reservation/FlightCard.tsx
> +			<Rectangle />
전체 컨테이너에 패딩값이 적용되어있어서 양쪽이 짤려서 rectangle을 주었습니다 ㅜㅜ

2024-11-26 08:55 UTC, KIMGEONHWI approved these changes

2024-11-26 09:26 UTC, merged